[Feature] Uploading casters' avatars
rcv-prod-toolkit/module-caster pull request #12
Opened 2023-09-07 10:13 UTC by 238SAMIxD

**Is your feature request related to a problem? Please describe.**
There was no option to upload casters' avatars.

**Describe the solution you'd like**
Displaying custom caster avatar next to their name instead of a logo from a theme. I reused some code from `Teams` module.

**Describe alternatives you've considered**
Manually changing source code to point to avatars.

**Additional context**
I also enhanced the look of the `img` to make it a circle
![image](https://github.com/rcv-prod-toolkit/module-caster/assets/46965900/5f93136d-f358-4a9b-84d9-51c0b863612f)
![image](https://github.com/rcv-prod-toolkit/module-caster/assets/46965900/a0e9906f-71ac-458b-b617-086e05d36f5d)

**Important**
I added and updated platforms to use font awesome icons so in the future more could be added. **_Font Awesome_ kit needs an update then because actual version does not support new `X-Twitter` icon**
![image](https://github.com/rcv-prod-toolkit/module-caster/assets/46965900/9bb7d9ae-c28d-494e-8211-5eca1597475d)

2023-09-07 18:02 UTC, Himyu commented
What happens if you don't upload a picture? Will it show the logo instead? Because we still need the option of just showing the logo for all that don't use pictures for their casters.

2023-09-07 18:29 UTC, 238SAMIxD commented
Yeah, I reverted hiding the logo

2023-09-07 18:39 UTC, 238SAMIxD commented
Should be fine now

2023-09-12 21:56 UTC, 238SAMIxD commented
Now it looks like that 
![image](https://github.com/rcv-prod-toolkit/module-caster/assets/46965900/914fdca3-88e0-475f-bbb3-85cc3689f2d2)
I guess there still be some problems with vertical images but I think people should use square/circle images

2023-09-20 21:11 UTC, 238SAMIxD commented
Is it possible to update `Font Awesome` kit to the version including the new X (Twitter) logo?

2023-09-23 00:43 UTC, Himyu commented
Yes, we could do that with an update to the main toolkit probably. Have to check first though.

2023-09-27 07:44 UTC, 238SAMIxD commented
Updating `.pug` as well as `frontend\gfx\gfx.html` - in this module, files should work

2023-10-01 12:13 UTC, Himyu requested changes

2023-10-09 19:39 UTC, Himyu approved these changes

2023-10-09 19:39 UTC, merged